%%{init: {'theme':'default'} }%%
flowchart TB
    classDef person fill:#08427b,stroke:#052e56,color:#ffffff
    classDef system fill:#1168bd,stroke:#0b4884,color:#ffffff
    classDef external fill:#999999,stroke:#6b6b6b,color:#ffffff

    Est["👤 Estudiante<br/><i>Solicita prestamos, reserva salas,<br/>consulta multas</i>"]:::person
    Bib["👤 Bibliotecario<br/><i>Aprueba prestamos, registra<br/>devoluciones, gestiona multas</i>"]:::person
    Adm["👤 Administrador<br/><i>Administra usuarios y politicas</i>"]:::person

    Sis["🟦 Sistema de Biblioteca CETYS<br/><i>Gestiona prestamos de libros,<br/>reservas y multas</i>"]:::system

    Cat["🟪 Catalogo CETYS<br/><i>Catalogo institucional<br/>de libros</i>"]:::external
    Pag["🟪 Sistema de Pagos Bancario<br/><i>Procesa cobros de fianzas<br/>y multas</i>"]:::external
    Dir["🟪 Directorio Estudiantil<br/><i>Autenticacion y datos<br/>de alumnos</i>"]:::external

    Est -->|Solicita prestamos / HTTPS| Sis
    Bib -->|Aprueba prestamos / HTTPS| Sis
    Adm -->|Administra / HTTPS| Sis

    Sis -->|Consulta libros<br/>SOAP| Cat
    Sis -->|Cobra fianzas<br/>HTTPS/REST| Pag
    Sis -->|Autentica usuarios<br/>LDAP| Dir
